### ISSUE TITLE
Kleinere CSS-Optimierungen

### ISSUE THREAD

**Issue by feststelltaste** [innoq/cards42org#12]
- Auf mobilen Endgeräten kann die Webseite horizontal bewegt / gescrollt werden
- Die Abstände zu den Rändern könnten noch einmal 1-2 px mehr sein

**Comment by erdlet** [comment]
Ich schau mir das mal an

**Comment by feststelltaste** [comment]
Danke, @erdlet!

![2019-07-09 18_00_46-Kudo](https://user-images.githubusercontent.com/1470822/60904656-ac781380-a273-11e9-8329-cac872f96ba9.png)
