### ISSUE TITLE
Beschreibungstext für #idol schreiben

### ISSUE THREAD

**Issue by feststelltaste** [innoq/cards42org#24]
![card19](https://user-images.githubusercontent.com/1470822/67844433-02f8ae80-fafe-11e9-8ca2-7773ee84fd9f.png)

Ergebnis bitte in den Branch `pack2` mergen.

**Comment by erdlet** [comment]
@feststelltaste Ich glaube, hier ist das falsche Bild referenziert?

**Comment by feststelltaste** [comment]
@erdlet Tatsächlich! Danke für den Hinweis! Fixed.
