### ISSUE TITLE
Beschreibungstext für #nutzen schreiben

### ISSUE THREAD

**Issue by feststelltaste** [innoq/cards42org#52]
<img width="298" alt="card30" src="https://user-images.githubusercontent.com/1470822/67186801-20849480-f3e9-11e9-9ccf-ced7b1a72880.png">

Ergebnis bitte in den Branch `pack2` mergen.

**Comment by erdlet** [comment]
In welcher Form wird das Ergebnis auf dieser Karte erwartet? Kann mir das gerade schwer vorstellen. 

Sollen hier die diskutierten Änderungen aufgeschrieben werden und nach Sichtbarkeit für den Kunden sortiert, oder irgendeine grafische Darstellung (in welcher Form auch immer) gewählt werden?

**Comment by feststelltaste** [comment]
Ersteres: Es sollen die Punkte, um die gerade diskutiert wird, entsprechend dem Nutzen / Sichtbarkeit für den Kunden aufgeschrieben werden. Z. B. so 
![grafik](https://user-images.githubusercontent.com/1470822/67199877-95b09380-f402-11e9-81a1-632aa379ed69.png)

**Comment by erdlet** [comment]
@programming-wolf Das Ticket kann dann geschlossen werden, oder?

**Comment by feststelltaste** [comment]
Hmm...gestern dachten wir, es wäre zu :-D
