### ISSUE TITLE
Provide English versions

### ISSUE THREAD

**Issue by JohannesPtaszyk** [innoq/cards42org#66]
The cards are super awesome and an amazing resource for everyone who has to deal with software architecture. 

To get the cards to even more people it would be nice to have translations.

The first language to support should be English, since it would open access for a lot of people.

**Comment by feststelltaste** [comment]
There we have the salad! No seriously, if everything works out, we'll start with an English version mid of 2020.

**Comment by feststelltaste** [comment]
Thanks for your feedback! A pure English online version could be a good and easy start. I've created a milestone (https://github.com/innoq/cards42org/milestone/4)  for it, so I'm closing this ticket.

In the meantime, let me think about how we can get this on the way and come back with some new tickets!

**Comment by feststelltaste** [comment]
@JohannesPtaszyk We are now officially working on it 😀 https://github.com/innoq/cards42org_en

**Comment by JohannesPtaszyk** [comment]
Nice! 🎉
Thank you for the great work! Keep it going!
